export const Cars = [
  {
    _id: "100",
    vehicle_type: "car",
    name: "Venue",
    properties: [
      { price: "10.12 - 17.87 Lakh" },
      { fuel: "Petrol" },
      { brand: "Hyundai" },
      { model: "S" },
      { year: "2020" },
    ],
    src: "https://imgd.aeplcdn.com/393x221/n/cw/ec/35455/venue-exterior-right-front-three-quarter-2.jpeg?q=85",
  },
  {
    _id: "101",
    vehicle_type: "car",
    name: "Kia Sonet",
    properties: [
      { price: "6.87 - 13.51 Lakh" },
      { fuel: "Petrol" },
      { brand: "Kia" },
      { model: "S" },
      { year: "2020" },
    ],
    src: "https://imgd.aeplcdn.com/393x221/n/cw/ec/41523/sonet-exterior-right-front-three-quarter-110.jpeg?q=85",
  },
  {
    _id: "102",
    vehicle_type: "car",
    name: "TaTa Nexon",
    properties: [
      { price: "7.3 - 13.35 Lakh" },
      { fuel: "Petrol" },
      { brand: "TaTa" },
      { model: "S" },
      { year: "2020" },
    ],
    src: "https://imgd.aeplcdn.com/393x221/n/cw/ec/41645/tata-nexon-right-front-three-quarter3.jpeg?q=85",
  },
  {
    _id: "103",
    vehicle_type: "car",
    name: "Kia Sonet",
    properties: [
      { price: "6.87 - 13.51 Lakh" },
      { fuel: "Petrol" },
      { brand: "Kia" },
      { model: "S" },
      { year: "2020" },
    ],
    src: "https://imgd.aeplcdn.com/393x221/n/cw/ec/41523/sonet-exterior-right-front-three-quarter-110.jpeg?q=85",
  },
  {
    _id: "104",
    vehicle_type: "car",
    name: "TaTa Nexon",
    properties: [
      { price: "7.3 - 13.35 Lakh" },
      { fuel: "Petrol" },
      { brand: "TaTa" },
      { model: "S" },
      { year: "2020" },
    ],
    src: "https://imgd.aeplcdn.com/393x221/n/cw/ec/41645/tata-nexon-right-front-three-quarter3.jpeg?q=85",
  },
  {
    _id: "105",
    vehicle_type: "car",
    name: "Venue",
    properties: [
      { price: "10.12 - 17.87 Lakh" },
      { fuel: "Petrol" },
      { brand: "Hyundai" },
      { model: "S" },
      { year: "2020" },
    ],
    src: "https://imgd.aeplcdn.com/393x221/n/cw/ec/35455/venue-exterior-right-front-three-quarter-2.jpeg?q=85",
  },
];
